### ISSUE TITLE
[SUB-TASK] Organize Google sheets into a pandas data frame and prepare to store it

### ISSUE THREAD

**Issue by noorbuchi** [GatorEducator/SheetShuttle#10]
## Parent Task (Where is this being split from)

#5 

## Sub-Task Description and Info (what needs to be done?)

Use pandas data frames to store the data.

## Acceptance Criteria (when is it considered complete?)

- [ ] Pandas is included in the poetry toml file and gets installed using poetry installl
- [ ] The collected data can be printed as a correctly formatted table in the terminal window
- [ ] Data can be accessed easily using column names and row  numbers

## Time to complete (approximately, how much time will this take?)

3 hrs

## Person/People involved (who is working on this?)

@antlet 

## Other information

Anything else that doesn't fit in previous categories
