### ISSUE TITLE
[TASK] Update GitHub Interactions Schema Documentation

### ISSUE THREAD

**Issue by noorbuchi** [GatorEducator/SheetShuttle#18]
## Task Description and Info (what needs to be done?)

`schemas.md` is currently not up to date with the incoming changes to github interactions. The documentations should be updated to help the user understand how sachems will be validated and the expected keys and values.

## Acceptance Criteria (when is it considered complete?)

- [ ] `schemas.md` contain a thorough description of all aspects of configuration in github interactions and github objects
  - [ ]  IssueEntry
  - [ ] PullRequestEntry
  - [ ] FileEntry
- [ ] The documentation is clear and free of grammar errors and spelling mistakes
- [ ] The documentation follows markdown lint rules and passes all the linter checks

## Time to complete (approximately, how much time will this take?)

Add estimate here

## Person/People involved (who is working on this?)

@

## Other information

Anything else that doesn't fit in previous categories
