### ISSUE TITLE
[TASK] Create Plugin Examples of GridGopher

### ISSUE THREAD

**Issue by noorbuchi** [GatorEducator/SheetShuttle#19]
## Task Description and Info (what needs to be done?)

The current documentation does not describe how the user can create a plugin and use the infrastructure and API provided by GridGopher. To assist with this issue, example guides can showcase code snippets with explanation of what they do and how the user can use this in their plugin. A simple tutorial of some sort should cover sheets collection and interacting with github using the Grid Gopher API.

## Acceptance Criteria (when is it considered complete?)

- [ ] The tutorial exists in the docs directory and is linked to from `README.md`
- [ ] The documentation is clear and free of grammar errors and spelling mistakes
- [ ] The documentation follows markdown lint rules and passes all the linter checks

## Time to complete (approximately, how much time will this take?)

Add estimate here

## Person/People involved (who is working on this?)

@

## Other information

Anything else that doesn't fit in previous categories

**Comment by noorbuchi** [comment]
It would be great if we can add more information on the available command line arguments
