### ISSUE TITLE
[TASK] Create GitHub Actions Workflow

### ISSUE THREAD

**Issue by noorbuchi** [GatorEducator/SheetShuttle#2]
## Task Description and Info (what needs to be done?)

To ensure that newly added changes are working and are up to standard, a GitHub Actions workflow should be used.
More information about GitHub Actions can be found [here](https://github.com/features/actions)

## Acceptance Criteria (when is it considered complete?)

- [ ] Actions are ran after every commit and a PR merge
- [ ] Workflow runs on at least two operating systems (Ubuntu and Mac)
- [ ] Workflow should use Python 3.8
- [ ] Supported linters are ran as part of the action
- [ ] Test suite is included in the action

## Time to complete (approximately, how much time will this take?)

Add estimate here

## Person/People involved (who is working on this?)

@

## Other information

Anything else that doesn't fit in previous categories
