### ISSUE TITLE
[TASK] Add Contributing Guidlines

### ISSUE THREAD

**Issue by noorbuchi** [GatorEducator/SheetShuttle#22]
## Task Description and Info (what needs to be done?)

There is currently no guidelines for new contributors to the project. Adding so would make the project more inviting for other to work with us. A contribution guidelines should include all the necessary information to set up a development environment and being work on the project, Additionally, it should inform the user of various quality assurance such as expected testing, coverage, and linting as well as describe the techniques we currently use to perform them. Other things to add would be how to go about picking an issue to work on and how to reach the developers with any questions. This will be a living document that gets updated frequently as we establish the guidelines for the project. All members of the development team should agree on its contents.

## Acceptance Criteria (when is it considered complete?)

- [ ] The documentation is free of spelling and grammar errors
- [ ] The documentation passes linter checks
- [ ] Documentation should be in `CONTRIBUTING.md` file

## Time to complete (approximately, how much time will this take?)

8-10 hours

## Person/People involved (who is working on this?)

@antlet 

## Other information

Anything else that doesn't fit in previous categories
