### ISSUE TITLE
[TASK] Run tests that include API calls in Github Actions only

### ISSUE THREAD

**Issue by noorbuchi** [GatorEducator/SheetShuttle#25]
## Task Description and Info (what needs to be done?)

Some test cases are somewhat slow because they make API calls to Google Sheets API or GitHub API. It's not necessary to run theses tests all the time when the developer run `poetry run test` or `poetry run coverage`. Instead, the user should specifically mention that all tests should be ran for these tests to run. Pytest, provides an easy way to mark tests in the code and to run specific ones from the CLI.

## Acceptance Criteria (when is it considered complete?)

- [ ] Mark all tests that perform API calls
- [ ] Update the commands in `pyproject.toml` to only run unmarked test
- [ ] Update the commands in GitHub actions to run ALL the tests

## Time to complete (approximately, how much time will this take?)

9 hours

## Person/People involved (who is working on this?)

@Yanqiao4396 

## Other information

Anything else that doesn't fit in previous categories
