### ISSUE TITLE
[TASK] Add test coverage calculation

### ISSUE THREAD

**Issue by noorbuchi** [GatorEducator/SheetShuttle#3]
## Task Description and Info (what needs to be done?)

Knowing test coverage is very important in understanding how effective our test suite is. A well known pytest plugin for calculating test coverage is `pytest-cov`. 

## Acceptance Criteria (when is it considered complete?)

- [ ] The dependency is added to the project's poetry files
- [ ] Test task includes argument to run pytest-cov
- [ ] Command runs without errors and with coverage information

## Time to complete (approximately, how much time will this take?)

Add estimate here

## Person/People involved (who is working on this?)

@

## Other information

Anything else that doesn't fit in previous categories
