### ISSUE TITLE
[TASK]Add GitHub Credentials and GitHub Configuration directory to Command Line Interface

### ISSUE THREAD

**Issue by noorbuchi** [GatorEducator/SheetShuttle#30]
## Task Description and Info (what needs to be done?)

Currently, the command line interface doesn't accept the location of github access token credentials, or the directory location for github configuration. Adding those as optional arguments is important.

## Acceptance Criteria (when is it considered complete?)

- [ ] The CLI accepts the two additional argument in a similar fashion as the Google Sheet arguments are
- [ ] Defaults values exist for the arguments and each one has a clear description
- [ ] The values retrieved from the arguments are passed into the run function of the plugin

## Time to complete (approximately, how much time will this take?)

3 hrs

## Person/People involved (who is working on this?)

@tuduun 

## Other information

Anything else that doesn't fit in previous categories
