### ISSUE TITLE
[SUB-TASK] Organize collected data and store in JSON and Pickle files

### ISSUE THREAD

**Issue by noorbuchi** [GatorEducator/SheetShuttle#8]
## Task Description and Info (what needs to be done?)

After the data is retrieved  from the API, it should be restructured in an intuitive and stored in JSON format.

Parent task: #5 

## Acceptance Criteria (when is it considered complete?)

- [ ] Pandas data frame is converted into dictionary
- [ ] The dictionary contains all information in the region
- [ ] Dictionary is written to JSON or Pickle file in a folder of user choice

## Time to complete (approximately, how much time will this take?)

2 hrs

## Person/People involved (who is working on this?)

@tuduun 
transferred to @noorbuchi 

## Other information

Anything else that doesn't fit in previous categories
