### ISSUE TITLE
[SUB-TASK] Give the user control over the cell range of the data, and data columns to store.

### ISSUE THREAD

**Issue by noorbuchi** [GatorEducator/SheetShuttle#9]
## Parent Task (Where is this being split from)

#5 

## Sub-Task Description and Info (what needs to be done?)

Read the remaining parts of the configuration file and come up with ways that give the user more control over what data to get from the sheets (open ended)

## Acceptance Criteria (when is it considered complete?)

- [ ] Read YAML for cell range
- [ ] Filter Pandas data frame based on the columns
- [ ] Optional but preferable: investigate how we can use `pluginbase` with this

## Time to complete (approximately, how much time will this take?)

5 hrs

## Person/People involved (who is working on this?)

@Yanqiao4396 

## Other information

Plugin base would allow the user to write their own plugins regarding what kinds of data columns to get and how to store them. Needs more investigation
